name: Build APK

on:
  push:
    branches:
      - main  # Ana branch'e yapılan her push işleminde tetiklenecek
  pull_request:
    branches:
      - main  # Pull request işlemlerinde de tetiklenebilir

jobs:
  build:
    runs-on: ubuntu-latest  # CI'nin çalışacağı ortam

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Android projeleri için genellikle Java 11 kullanılır

      - name: Set up Android SDK
        uses: react-native-community/ci-config@v1
        with:
          android-sdk-version: '30.0.3'  # Android SDK sürümü

      - name: Build APK
        run: ./gradlew assembleRelease  # APK'yı build etmek için gradle komutu

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloudstream-apk
          path: app/build/outputs/apk/release/app-release.apk  # Oluşturulan APK'nın yolu
